name: Static Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis-phpstan:
    name: Static Analysis with PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: phpstan, cs2pr
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: '${{ steps.composer-cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-${{ hashFiles(''**/composer.json'') }}'
          restore-keys: '${{ runner.os }}-composer-'

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan
        run: >-
          phpstan analyse -c phpstan.neon --no-progress --no-interaction
          --error-format=checkstyle | cs2pr

  static-analysis-psalm:
    name: Static Analysis with Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: psalm, cs2pr
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Psalm
        run: psalm --show-info=false --output-format=checkstyle --shepherd | cs2pr

  static-analysis-php-metrics:
    name: Static Analysis with PhpMetrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          composer require --dev phpmetrics/phpmetrics ^2.6

      - name: Run PhpMetrics
        run: ./vendor/bin/phpmetrics --exclude=Exception src

  static-analysis-composer-require-checker:
    name: Static Analysis with ComposerRequireChecker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          composer require --dev maglnet/composer-require-checker ^2.0

      - name: Run composer-require-checker
        run: ./vendor/bin/composer-require-checker check --config-file=./php-require-checker.config.json ./composer.json
